site_name: NSHBR
copyright: © Copyright 2019, MrT, NSHBR

extra:
  social:
    - type: 'discord'
      link: 'https://discord.gg/QXegbwU' 

markdown_extensions:
  - admonition

theme:
  favicon: 'assets/images/favicon.ico' 
  language: 'pt'
  logo: 'images/logo.svg'
  name: material
  palette:
    primary: 'green'
    accent: 'pink'
    
repo_name: 'mrtzera/nshbr-guia'
repo_url: 'https://github.com/mrtzera/nshbr-guia'   
   
nav:
- Bem-vindo: index.md
- Introdução: Introdução.md
- Meu Switch é desbloqueável?: Meu switch é desbloqueável.md
- fusee-gelee: fusee-gelee.md
- Deja-vu: Deja-vu.md


