site_name: NSHBR - Guia

extra:
  social:
    - type: 'discord'
      link: 'https://discord.gg/QXegbwU' 

markdown_extensions:
  - admonition

theme:
  language: 'pt'
  logo: 'images/logo.svg'  
  name: material
  palette:
    primary: 'red'
    accent: 'blue'
    
repo_url: https://github.com/mrtzera/nshbr-guia
    
   
    


